# Generated by Django 3.0.3 on 2020-06-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_title', models.CharField(max_length=100, verbose_name='Название голосования')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала голосования')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца голосования')),
                ('limit_of_votes', models.IntegerField(default=10, verbose_name='Количество голосов для завершения')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('person_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('person_patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('person_photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionsApp.Vote')),
            ],
        ),
    ]
