# Generated by Django 3.0.3 on 2020-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='vote',
            new_name='vote_id',
        ),
        migrations.AddField(
            model_name='person',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голосов'),
        ),
    ]
