# Generated by Django 3.0.3 on 2020-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionsApp', '0002_auto_20200702_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
        migrations.AddField(
            model_name='person',
            name='person_bio',
            field=models.CharField(default=0, max_length=200, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
