# Generated by Django 3.0.3 on 2020-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionsApp', '0003_auto_20200702_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
